# Generated by Django 3.2.14 on 2022-10-11 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0076_modellogentry_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIntegrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дата обновления')),
                ('data', models.JSONField(verbose_name='Сырые данные')),
                ('status', models.IntegerField(choices=[(0, 'Сообщение МС получено'), (1, 'Сообщение МС получено. Сообщение корректно'), (-1, 'Сообщение MC получено. Сообщение не корректно'), (2, 'Сообщение разбито по объектам'), (-2, 'Ошибка разбиения по объектам'), (3, 'Обработано'), (-3, 'Обработано с ошибками')], default=0, verbose_name='Статус')),
                ('status_details', models.TextField(blank=True, null=True, verbose_name='Детали статуса')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawintegrationdata_created', to=settings.AUTH_USER_MODEL)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawintegrationdata_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сырые интеграционные данные',
                'verbose_name_plural': 'Сырые интеграционные данные',
            },
        ),
        migrations.CreateModel(
            name='IntegrationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дата обновления')),
                ('data', models.JSONField(verbose_name='json экземпляра объекта')),
                ('status', models.IntegerField(choices=[(0, 'В ожидании обработки'), (1, 'В процессе обработки'), (-2, 'Ошибка обработки'), (2, 'Обработано')], default=0, verbose_name='Статус')),
                ('status_details', models.TextField(blank=True, null=True, verbose_name='Детали статуса')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrationinstance_created', to=settings.AUTH_USER_MODEL)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('raw_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.rawintegrationdata', verbose_name='Необработанная запись')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrationinstance_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Экземпляр объекта интеграции',
                'verbose_name_plural': 'Экземпляры объектов интеграции',
            },
        ),
    ]
